name: irbuilder
version: '0.1.0.0'
author: Stephen Diehl, Olle Fredriksson
license: MIT
dependencies:
- base ==4.9.*
- transformers
- mtl
- bytestring
- text
- containers
- unordered-containers
- llvm-hs-pure
- llvm-hs-pretty
library:
  ghc-options:
    -fwarn-incomplete-patterns
  exposed-modules:
  - IRBuilder
