resolver: lts-9.10

packages:
- '.'
extra-deps:
- git: https://github.com/llvm-hs/llvm-hs.git
  commit: 29c584b28800be81229f2c04e71ff2bb130407a5
  subdirs:
    - llvm-hs-pure

flags: {}
extra-package-dbs: []
