resolver: lts-9.10

packages:
- '.'
- location:
    git: https://github.com/llvm-hs/llvm-hs-pretty.git
    commit: f5093c8e53fe8eb8bf384a44df2e9cf6d8c2983d
  extra-dep: true

extra-deps:
- llvm-hs-pure-5.1.0

flags: {}
extra-package-dbs: []
